on: push

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: HTML Preview
        uses: pavi2410/html-preview-action@v4
        with:
          html_file: SurgicalSync/index.html
          job_summary: true
              
